String.toLocaleString({
    
	"it": {
		"%game-intro"           : "Join the <strong>SuperHeels!</strong>",
		"%restart-button"       : "Retry",
		"%keep-playing-button"  : "Continue",
		"%retry-button"         : "Retry",
		"%game-won"             : "You win!",
		"%game-over"            : "Game over!",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two shoes touch, they <strong>get better!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/superheels\">git.io/superheels</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%credits"              : "SuperHeels images by <a href=\"http://www.heels.com/\" title=\"Heels.com | About\">Heels.com</a>.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-SuperHeels #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : 'blue birthday',
    '%4'                    : 'bubblegum apple',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'blonde ganache',
    '%32'                   : 'zebra zebra',
    '%64'                   : 'black sandal',
    '%128'                  : 'super pois',
    '%256'                  : 'perfect soiree',
    '%512'                  : 'ireland witch',
    '%1024'                 : 'super glam',
    '%2048'                 : 'sixties flower',
		'%p0'                   : 'blue birthday',
    '%p4'                   : 'bubblegum apple',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'blonde ganache',
    '%p32'                  : 'zebra zebra',
    '%p64'                  : 'black sandal',
    '%p128'                 : 'super pois',
    '%p256'                 : 'perfect soiree',
    '%p512'                 : 'ireland witch',
    '%p1024'                : 'super glam',
    '%p2048'                : 'sixties flower',
	},
	
	"en": {
	   "%game-intro"           : "Join the <strong>SuperHeels!</strong>",
        "%restart-button"       : "Retry",
        "%keep-playing-button"  : "Continue",
        "%retry-button"         : "Retry",
        "%game-won"             : "You win!",
        "%game-over"            : "Game over!",
        "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two shoes touch, they <strong>get better!</strong>",
        "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/superheels\">git.io/superheels</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
        "%credits"              : "SuperHeels images by <a href=\"http://www.heels.com/\" title=\"Heels.com | About\">Heels.com</a>.",
        "%tweet1"               : "I scored \"",
        "%tweet2"               : "\" at 2048-SuperHeels #2048game",
        "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
        '%2'                    : 'blue birthday',
    '%4'                    : 'bubblegum apple',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'blonde ganache',
    '%32'                   : 'zebra zebra',
    '%64'                   : 'black sandal',
    '%128'                  : 'super pois',
    '%256'                  : 'perfect soiree',
    '%512'                  : 'ireland witch',
    '%1024'                 : 'super glam',
    '%2048'                 : 'sixties flower',
        '%p0'                   : 'blue birthday',
    '%p4'                   : 'bubblegum apple',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'blonde ganache',
    '%p32'                  : 'zebra zebra',
    '%p64'                  : 'black sandal',
    '%p128'                 : 'super pois',
    '%p256'                 : 'perfect soiree',
    '%p512'                 : 'ireland witch',
    '%p1024'                : 'super glam',
    '%p2048'                : 'sixties flower',
	}

});